services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.6.0
    command:
      - /usr/local/bin/etcd
      - --name=etcd
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-token=blockchain-node-admin
      - --initial-cluster-state=new
    volumes:
      - etcd_data:/etcd-data
    ports:
      - "2379:2379"

  apisix:
    image: apache/apisix:3.0.0-debian
    restart: unless-stopped
    volumes:
      - ./etc/apisix_conf.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"
      - "9180:9180"
    depends_on:
      - etcd

  dashboard:
    build:
       context: ./
       dockerfile: Dockerfile
       #no_cache: true
    restart: unless-stopped
    volumes:
      - ./etc/dashboard_conf:/usr/local/apisix-dashboard/conf/
    ports:
      - "10001:9000"
    depends_on:
      - etcd
      - apisix

  dashboard-local:
    build:
       context: ./
       dockerfile: Dockerfile.local
    restart: unless-stopped
    environment:
      DASHBOARD_NODE_MAX_OLD_SPACE_SIZE: "4096"
    volumes:
      - ./:/usr/local/apisix-dashboard
      - ./etc/dashboard_conf:/usr/local/apisix-dashboard/conf/
      - dashboard_local_go_mod:/go/pkg/mod
      - dashboard_local_go_build:/root/.cache/go-build
      - dashboard_local_node_modules:/usr/local/apisix-dashboard/web/node_modules
    ports:
      - "10001:9000"
    depends_on:
      - etcd
      - apisix

volumes:
  etcd_data:
  dashboard_local_go_mod:
  dashboard_local_go_build:
  dashboard_local_node_modules:
